from enum import StrEnum


class CustomerStatus(StrEnum):
    ACTIVE = "ACTIVE"
    PAST_DUE = "PAST_DUE"
    CHURN_RISK = "CHURN_RISK"


class PaymentStatus(StrEnum):
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    RECOVERED = "RECOVERED"
    CANCELED = "CANCELED"


class FailureReason(StrEnum):
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    EXPIRED_CARD = "EXPIRED_CARD"
    CARD_DECLINED = "CARD_DECLINED"
    PROCESSOR_ERROR = "PROCESSOR_ERROR"
    AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"


class RecoveryCaseStatus(StrEnum):
    DETECTED = "DETECTED"
    ANALYZING = "ANALYZING"
    ACTION_REQUIRED = "ACTION_REQUIRED"
    RECOVERED = "RECOVERED"
    ESCALATED = "ESCALATED"
    STOPPED = "STOPPED"


class RecoveryActionType(StrEnum):
    RETRY_PAYMENT = "RETRY_PAYMENT"
    SEND_PAYMENT_LINK = "SEND_PAYMENT_LINK"
    ESCALATE = "ESCALATE"
    STOP = "STOP"


class RecoveryActionStatus(StrEnum):
    PROPOSED = "PROPOSED"
    APPROVED = "APPROVED"
    EXECUTED = "EXECUTED"
    BLOCKED = "BLOCKED"


class DecisionStatus(StrEnum):
    PROPOSED = "PROPOSED"
    VALIDATED = "VALIDATED"
    REJECTED = "REJECTED"


class RiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class AuditEventType(StrEnum):
    CASE_CREATED = "CASE_CREATED"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    ACTION_SEEDED = "ACTION_SEEDED"
    DECISION_SEEDED = "DECISION_SEEDED"
    AI_ANALYSIS_COMPLETED = "AI_ANALYSIS_COMPLETED"
    AI_ANALYSIS_FAILED = "AI_ANALYSIS_FAILED"
